language: node_js

node_js:
  - "0.10"
  - "4"

matrix:
  allow_failures:
   - node_js: "4"

addons:
  apt:
    packages:
      - dh-make
      - devscripts
      - debhelper
      - git

after_success:
 - ./node_modules/.bin/istanbul cover -x "**/spec/**" ./node_modules/.bin/_mocha --report lcovonly -- $(find spec -name '*-spec.js') -R spec --require spec/helper.js
 - cat ./coverage/lcov.info | node_modules/.bin/coveralls

before_deploy:
 - npm prune --production
 - mkdir -p packagebuild deb
 - cp -ar !(packagebuild) packagebuild/
 - pushd packagebuild
 - git log -n 1 --pretty=format:%h.%ai.%s > commitstring.txt
 - export DEBFULLNAME=`git log -n 1 --pretty=format:%an`
 - export DEBEMAIL=`git log -n 1 --pretty=format:%ae`
 - dch -l `echo "${TRAVIS_BRANCH}" | sed 's/[\/\_]/-/g'` -u low `git log -n 1 --pretty=oneline --abbrev-commit`
 - debuild --no-lintian --no-tgz-check -us -uc
 - popd
 - cp -a *.deb deb/

deploy: 
  provider: bintray
  file: .bintray.json
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  on:
    branch: master
    node: "0.10"

notifications:
  slack:
    rooms:
    - secure: "ujMcSsKW1N8S/81CI1RFH073O9d4fJZr+dRFiFveh8vlfO1aFerNyvR4xkDmQ3ZTX/gEiwfijlv5KHSbJuRYx4bW6NR/oELLcjUGAG4mlZ9+FEOE5+Ep8kaYso/onx49cPgmFKl086m5pafWjcewqdGS07779QZkrSYAZmZNXIvwYJKBhlunXHv2yhjP2whBYcXVClq5zWh7Rh35keBrT60B0g+6boU2MbrP0mLMFFsx8i9o8AiecMZtkgel1B5TjpaIr6FjHX2nh4InR5siBDyWHu3Wxsnwa2fHfp6Y2roZx2PB8XuYFKDU0Tr8vT1h3sSNklwBcDdQnvBUFvQbvt/rRrdfYdVE8vciwempC3maCQgZK0JcukrOx9dJP6b83mqp/H1v6owStRq0IbGe+k0NB29V0lwhIbIPFfsmjGnYX0bJHtHx1Dr1aM1ilYEhm/N1YqPKAOXwItCrBDmI/5YpyFP1mOSBYWmf7C4SZU2vxCIJDWWMsXXljfzihux5Tgpsn+cnDiQsMVlAmdPE6deqeXP/+P8Rk9qEzmo5OrtkKsPLu7Af2tksOOFs1XL9/Z7GM7Q6f+xMNzV/CLklNi9i9c7YxwWthZIC7GTx+inPwizzflPDas66GgwS+oVbb1BBbKuXOLx8JYYOegssdKWoZg2ZAw3l1DgUacb5Vic="
    on_success: never
    on_failure: always
    on_start: never
